name: FREE - STATE
favicon: null
layout_spectrum: 0.5782754281535745
typography_spectrum: 0.07004510704427958
title: A State Of Mind. A State Of Existence.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.941386847756803
  lightness: 0.023719883989542723
  saturation: 0.7892066836357117
  rhythmicContrast: 0.27944112522527575
purpose: []
