name: FREE - STATE
favicon: null
layout_spectrum: 0.9249578
typography_spectrum: 0.4182125
title: A State Of Mind. A State Of Existence.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BDC7C6'
    - '#909188'
    - '#3A4142'
    - '#A4425C'
    - '#FA6380'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
